### ISSUE TITLE
Can't load DynamoDB table data

### ISSUE THREAD

**Issue by parthipank** [dbeaver/cloudbeaver#399]
**Describe the bug**
DynamoDB table data is not getting loaded when the table is selected from the list. Other tables are loading the data totally fine. There are no error logs to find out what is going wrong. The particular DynamoDB table is currently filled with more than 300 records and can be viewed in the amazon console without any hassle.

The exact table couldn't be loaded in the dBeaver EE desktop version too with some errors couple of months back, where I reported a bug and got it fixed and works fine now. 
Issue Link: https://github.com/dbeaver/dbeaver/issues/11772

Version Used: CloudBeaver in AWS (Cloud Image)

**To Reproduce**
1. Click on the particular table from the DynamoDB table list from the left panel
2. No errors in the logs. (Shows "Tasks execution returns no result") Refer the screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/10793238/123556795-f503a100-d7aa-11eb-9b40-fc160da78b53.png)

**Comment by uslss** [comment]
thank you for the report

**Comment by serge-rider** [comment]
This bug was fixed in the desktop version 21.1.0. The fix will be included in cloud version 21.1 as well (release planned on late June).

**Comment by parthipank** [comment]
> This bug was fixed in the desktop version 21.1.0. The fix will be included in cloud version 21.1 as well (release planned on late June).

Thank you. Eagerly waiting for the release.

**Comment by kseniiaguzeeva** [comment]
The release is published.

**Comment by parthipank** [comment]
@kseniiaguzeeva Will this release reflect in the latest cloudbeaver version in AWS? It still shows the version from April 26.
![image](https://user-images.githubusercontent.com/10793238/125894067-e3168ef0-165e-4c10-a6fb-0992c7b8ad78.png)

**Comment by kseniiaguzeeva** [comment]
I apologize for the hasty news. Community version of the product is published. And we're placing CloudBeaver AWS on the Amazon Marketplace now. I will write to you as soon as the latest version will be available there

**Comment by parthipank** [comment]
> I apologize for the hasty news. Community version of the product is published. And we're placing CloudBeaver AWS on the Amazon Marketplace now. I will write to you as soon as the latest version will be available there

Thank You :)

**Comment by kseniiaguzeeva** [comment]
CloudBeaver AWS 21.1.0 has been published
